repos:
-   repo: https://github.com/pre-commit/pre-commit.git
    sha: v1.8.2
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v1.2.3
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: detect-private-key
    -   id: detect-aws-credentials
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
    -   id: flake8
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        files: '\.py$'
-   repo: git://github.com/pre-commit/mirrors-yapf
    sha: v0.21.0
    hooks:
    -   id: yapf
        args: [-i]
