# https://duo.fyi/pullapprove
groups:
  repo-checkers:
    suggested_users:
      - caleb.noble@duolingo.com
      - david.sawicki@duolingo.com
      - josh@duolingo.com
      - shelby@duolingo.com
    users:
      - aaron.wang@duolingo.com
      - caleb.noble@duolingo.com
      - david.sawicki@duolingo.com
      - guanhua@duolingo.com
      - hideki@duolingo.com # Backup repo-checker
      - josh@duolingo.com
      - nancy@duolingo.com
      - peter@duolingo.com
      - shelby@duolingo.com
      - yijin@duolingo.com
  feature-watchers:
    conditions:
      files:
        - jeeves/config/jira_features.py
    required: 0
    users:
      - hideki@duolingo.com
    comment: |
      ## Important reminders when modifying the feature list

      If you're renaming a feature from the list, you need to:
       - [File a ticket with a Jira admin](https://duolingo.atlassian.net/jira/core/projects/JIRA/form/3) to rename the feature **before** you merge this PR. Otherwise, a new feature will be created with the new name.
       - After the PR is merged, run [this Jenkins Job](https://jenkins-ci.duolingo.com/job/duolingo-jeeves-refresh-tickets/) to refresh the name of the feature on existing Jira issues.

      If you're removing a feature from the list, you need to:
       - Move all tickets with that feature in Jira to a new feature or close them.
       - [File a ticket with a Jira admin](https://duolingo.atlassian.net/jira/core/projects/JIRA/form/3) to remove the feature from the Jira dropdown too. Removing it from here will only remove it from shake-to-report.

      Also, please check if any Jira Automations, filters, or whatever JQLs relying on Jira Feature needs to be update.

      Example resources:
       - [Jira Automation to post issues with Feature to Slack Channel](https://duolingo.atlassian.net/wiki/spaces/DUO/pages/2585821214/Create+Jira+Automation+to+post+issues+with+Feature+to+Slack+Channel)
       - (Growth Area only) [Jira Automation for team assignment](https://docs.google.com/document/d/1U7oqS7rr-V4eWAYbXrzGXmQVPfHRnar1QuP3qUqOyTY/edit?usp=sharing)

      Please leave a thumbs-up reaction to confirm that you've read this.
