# PullApprove repo config. https://docs.pullapprove.com/
version: 2
extends: standard # https://pullapprove.com/duolingo/
groups:
  repo-checkers:
    users:
      - hidekishima
      - GroundPound
      - ppearsonDuolingo
