FROM node:16.13.1-alpine3.15 AS web-requirements

WORKDIR /code
COPY web/package.json .
COPY web/package-lock.json .
RUN npm ci

FROM node:16.13.1-alpine3.15 AS web-builder

WORKDIR /code
COPY web .
COPY --from=web-requirements /code/node_modules ./node_modules
RUN rm -rf dist && \
  "$(npm bin)/tsc" -p config && \
  "$(npm bin)/webpack" --config config/webpack.config.js --mode production --env excess_mode="debug"

FROM ubuntu:20.04

# Opentelemetry Configuration
ENV OTEL_LOGS_EXPORTER none
ENV OTEL_METRICS_EXPORTER none
ENV OTEL_TRACES_EXPORTER otlp,console
ENV OTEL_EXPORTER_OTLP_ENDPOINT 172.17.0.1:4317
ENV OTEL_EXPORTER_OTLP_INSECURE true
ENV OTEL_EXPORTER_OTLP_PROTOCOL grpc
ENV OTEL_EXPORTER_OTLP_TIMEOUT 1
ENV OTEL_SERVICE_NAME jeeves
ENV OTEL_TRACES_SAMPLER parentbased_traceidratio
ENV OTEL_TRACES_SAMPLER_ARG 1
ENV OTEL_PROPAGATORS tracecontext,baggage,jaeger


ENV INSTALL_PATH /code
ENV DEV_REQ_TXT dev-requirements.txt
ENV PYTHONIOENCODING UTF-8
ENV DUOLINGO_CONFIG=${INSTALL_PATH}/config/dev.yml
ENV PYTHONPATH /code

WORKDIR $INSTALL_PATH

# Modified techniques from:
# https://blog.codeship.com/alpine-based-docker-images-make-difference-real-world-apps/

COPY $DEV_REQ_TXT $DEV_REQ_TXT

RUN mkdir -p data/zendesk

RUN apt-get update \
 && apt-get -y --no-install-recommends install \
      build-essential \
      python3-dev \
      python3-pip \
#     libpq-dev is a postgres library needed by sqlalchemy
      libpq-dev \
#     necessary for weasyprint to create pdf files for bug reports
      libpango-1.0-0 \
      libharfbuzz0b \
      libpangoft2-1.0-0 \
 && rm -rf /var/lib/apt/lists/* \
 && ln -s /usr/bin/python3 /usr/bin/python

RUN pip3 install -U pip pip-tools wheel \
 && pip3 install \
      awscli \
      setuptools

ARG REQUIREMENTS=dev-requirements.txt
COPY $REQUIREMENTS $REQUIREMENTS
RUN pip3 install -r "$REQUIREMENTS" --src /usr/local/src

# Import duplicate detector model
ENV DUPLICATE_DETECTOR_MODEL=/opt/jeeves/duplicate-detector-model/
ENV S3_FILE_STORAGE="s3://jeeves-document-cache"
ENV DUPLICATE_DETECTOR_REMOTE_PATH="$S3_FILE_STORAGE/duplicate-detector-model"
ARG aws_access_key
ARG aws_secret_key
ENV AWS_ACCESS_KEY_ID $aws_access_key
ENV AWS_SECRET_ACCESS_KEY $aws_secret_key
RUN aws s3 sync "$DUPLICATE_DETECTOR_REMOTE_PATH" $DUPLICATE_DETECTOR_MODEL

# Import priority estimator model
ENV PRIORITY_ESTIMATOR_MODEL=/opt/jeeves/priority_estimator_model/
ENV PRIORITY_ESTIMATOR_REMOTE_PATH="$S3_FILE_STORAGE/priority_estimator_model"
RUN aws s3 sync "$PRIORITY_ESTIMATOR_REMOTE_PATH" $PRIORITY_ESTIMATOR_MODEL

COPY . .
COPY --from=web-builder /code/dist ./web/dist

EXPOSE 5000

CMD ["opentelemetry-instrument",  "uwsgi", "uwsgi_dev.ini"]
