version: "2"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    image: duolingojeeves_api
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - ~/.aws:/root/.aws

  s3-worker:
    image: duolingojeeves_api
    volumes:
      - .:/code
      - ~/.aws:/root/.aws
    command: ["python", "./jeeves/scripts/update_jeeves_data.py"]
    build:
      context: .
      dockerfile: Dockerfile.dev

  sqs-worker-1:
    image: duolingojeeves_api
    volumes:
      - .:/code
      - ~/.aws:/root/.aws
    command: ["python", "/code/jeeves/scripts/sqs_verify_worker.py"]
    build:
      context: .
      dockerfile: Dockerfile.dev

  sqs-worker-2:
    image: duolingojeeves_api
    volumes:
      - .:/code
      - ~/.aws:/root/.aws
    command: ["python", "/code/jeeves/scripts/sqs_index_worker.py"]
    build:
      context: .
      dockerfile: Dockerfile.dev

  spike-worker:
    image: duolingojeeves_api
    volumes:
      - .:/code
      - ~/.aws:/root/.aws
    command: ["python", "/code/jeeves/scripts/spike_worker.py"]
    build:
      context: .
      dockerfile: Dockerfile.dev
