version: "3.8"

networks:
  localstack-net:
  memcached-net:
  opensearch-net:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: duolingojeeves_api_local
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./config/aws_credentials_local:/root/.aws/credentials
    depends_on:
      opensearch-ready:
        condition: service_healthy
      localstack:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - AWS_DEFAULT_PROFILE
      - AWS_SECRET_ACCESS_KEY
      - DUOLINGO_CONFIG
      - DUOLINGO_JWT
      - JIRA_API_TOKEN
      - JIRA_USERNAME
      - SHAKIRA_JIRA_API_TOKEN_WEB=${JIRA_API_TOKEN}
      - SHAKIRA_JIRA_USERNAME_WEB=${JIRA_USERNAME}
    healthcheck:
      interval: 10s
      retries: 12
      start_period: 60s
      test: curl --fail "http://opensearch:9200/jeeves_spikes_v_${DATA_VERSION_IDENTIFIER}"
      timeout: 5s
    networks:
      - localstack-net
      - memcached-net
      - opensearch-net
    restart: on-failure

  memcached:
    container_name: memcached
    image: memcached:1.6.21
    networks:
      - memcached-net
    ports:
      - "11211:11211"

  opensearch:
    container_name: opensearch
    environment:
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=opensearch
      - cluster.name=vpc-duolingo-jeeves-es-local
      - discovery.seed_hosts=
      - node.name=opensearch
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # Disables Security plugin to make local development less complicated
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      interval: 10s
      retries: 12
      start_period: 60s
      test: curl --output /dev/null --silent --fail -X GET "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s"
      timeout: 10s
    hostname: opensearch
    image: opensearchproject/opensearch:1
    networks:
      - opensearch-net
    ports:
      - "9200:9200" # REST API
      - "9600:9600" # Performance Analyzer
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  opensearch-dashboards: # OpenSearch version of Kibana
    container_name: opensearch-dashboards
    depends_on:
      opensearch:
        condition: service_healthy
    environment:
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true # disables security dashboards plugin in OpenSearch Dashboards
      - OPENSEARCH_HOSTS=http://opensearch:9200
    expose:
      - "5601"
    healthcheck:
      interval: 30s
      retries: 3
      test: curl --fail http://localhost:5601/api/status
      timeout: 10s
    image: opensearchproject/opensearch-dashboards:1
    networks:
      - opensearch-net
    ports:
      - "5601:5601"

  # A wrapper around OpenSearch to check that the domain we're creating is green before starting the API service
  opensearch-ready:
    container_name: opensearch-ready
    depends_on:
      opensearch:
        condition: service_healthy
      opensearch-dashboards:
        condition: service_healthy
    entrypoint: /home/curl_user/scripts/init.sh
    healthcheck:
      interval: 10s
      retries: 12
      start_period: 60s
      test: curl --output /dev/null --silent --fail -X GET "http://opensearch:9200/_cluster/health?wait_for_status=green&timeout=5s"
      timeout: 10s
    image: curlimages/curl:8.1.1
    networks:
      - opensearch-net
    volumes:
      - ./scripts/opensearch:/home/curl_user/scripts

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - AWS_SECRET_ACCESS_KEY
      - DATA_VERSION_IDENTIFIER
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DUOLINGO_CONFIG
      - HOSTNAME=localstack
      - LOCALSTACK_HOST=localstack
      - LS_LOG=warn
      - USER_AWS_ACCESS_KEY_ID
      - USER_AWS_SECRET_ACCESS_KEY
    healthcheck:
      interval: 10s
      retries: 24
      start_period: 2m
      test: curl --fail --output /dev/null --silent -X POST "http://localstack:4566/queue/us-east-1/000000000000/jeeves-pipeline-break-verify-index-local" -d "Action=GetQueueAttributes&Version=2012-11-05&AttributeName.1=All"
      timeout: 5s
    image: "localstack/localstack:2.0.2"
    networks:
      - localstack-net
      - opensearch-net
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./scripts/localstack:/etc/localstack/init/ready.d
      - ./config:/home/localstack/config

  s3-worker:
    build:
      context: .
      dockerfile: Dockerfile.local
    command:
      [
        "python",
        "./jeeves/scripts/index_pipeline_and_spike_detector/update_jeeves_data.py",
      ]
    depends_on:
      api:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: any
        delay: 1m
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - AWS_DEFAULT_PROFILE
      - AWS_SECRET_ACCESS_KEY
      - DUOLINGO_CONFIG
      - JIRA_API_TOKEN
      - JIRA_USERNAME
      - LOG_LEVEL=debug
    image: duolingojeeves_api_local
    networks:
      - localstack-net
      - opensearch-net
    volumes:
      - .:/code
      - ./config/aws_credentials_local:/root/.aws/credentials

  spike-worker:
    image: duolingojeeves_api_local
    command:
      [
        "python",
        "/code/jeeves/scripts/index_pipeline_and_spike_detector/spike_worker.py",
        "True",
      ]
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      api:
        condition: service_healthy
      sqs-worker-2:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - AWS_DEFAULT_PROFILE
      - AWS_SECRET_ACCESS_KEY
      - DUOLINGO_CONFIG
      - DUOLINGO_JWT
    networks:
      - localstack-net
      - opensearch-net
    restart: always
    volumes:
      - .:/code
      - ./config/aws_credentials_local:/root/.aws/credentials

  sqs-worker-1:
    build:
      context: .
      dockerfile: Dockerfile.local
    command:
      [
        "python",
        "/code/jeeves/scripts/index_pipeline_and_spike_detector/sqs_verify_worker.py",
      ]
    depends_on:
      api:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - AWS_DEFAULT_PROFILE
      - AWS_SECRET_ACCESS_KEY
      - DUOLINGO_CONFIG
      - JIRA_API_TOKEN
      - JIRA_USERNAME
    image: duolingojeeves_api_local
    networks:
      - localstack-net
      - opensearch-net
    restart: on-failure
    volumes:
      - .:/code
      - ./config/aws_credentials_local:/root/.aws/credentials

  sqs-worker-2:
    command:
      [
        "python",
        "/code/jeeves/scripts/index_pipeline_and_spike_detector/sqs_index_worker.py",
      ]
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      api:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - AWS_DEFAULT_PROFILE
      - AWS_SECRET_ACCESS_KEY
      - DATA_VERSION_IDENTIFIER
      - DUOLINGO_CONFIG
      - DUOLINGO_JWT
    healthcheck:
      # Check that we have a document in the index. JIRA_247210 should have come from S3 on 2023-05-01 (this is DLAA-19036)
      interval: 10s
      retries: 15
      start_period: 5m
      test: curl --fail --silent -X GET "http://opensearch:9200/jeeves_tickets_v_${DATA_VERSION_IDENTIFIER}/_doc/JIRA_247210"
      timeout: 5s
    image: duolingojeeves_api_local
    networks:
      - localstack-net
      - opensearch-net
    restart: on-failure
    volumes:
      - .:/code
      - ./config/aws_credentials_local:/root/.aws/credentials

volumes:
  opensearch-data:
