FROM node:12.13.1-alpine3.10 AS web-requirements

WORKDIR /code
COPY web/package.json .
COPY web/package-lock.json .
RUN npm ci

FROM node:12.13.1-alpine3.10 AS web-builder

WORKDIR /code
COPY web .
COPY --from=web-requirements /code/node_modules ./node_modules
RUN rm -rf dist && \
  "$(npm bin)/tsc" -p config && \
  "$(npm bin)/webpack" --config config/webpack.config.js --mode production

FROM ubuntu:18.04

ENV INSTALL_PATH /code
ENV DEV_REQ_TXT dev-requirements.txt
ENV PYTHONIOENCODING UTF-8
ENV DUOLINGO_CONFIG=${INSTALL_PATH}/config/dev.yml
ENV PYTHONPATH /code

WORKDIR $INSTALL_PATH

# Modified techniques from:
# https://blog.codeship.com/alpine-based-docker-images-make-difference-real-world-apps/

COPY $DEV_REQ_TXT $DEV_REQ_TXT

RUN mkdir -p data/zendesk

RUN apt-get update \
 && apt-get -y --no-install-recommends install \
      build-essential \
      python3-dev \
      python3-pip \
#     libpq-dev is a postgres library needed by sqlalchemy
      libpq-dev \
      curl \
      unzip \
 && rm -rf /var/lib/apt/lists/* \
 && ln -s /usr/bin/python3 /usr/bin/python

RUN pip3 install -U pip pip-tools wheel \
 && pip3 install setuptools==49.6.0

ARG REQUIREMENTS=dev-requirements.txt
COPY $REQUIREMENTS $REQUIREMENTS
RUN pip3 install -r "$REQUIREMENTS" --src /usr/local/src

# Import duplicate detector model
ENV DUPLICATE_DETECTOR_MODEL=/opt/jeeves/duplicate-detector-model/
ENV S3_FILE_STORAGE="s3://jeeves-document-cache"
ENV DUPLICATE_DETECTOR_REMOTE_PATH="$S3_FILE_STORAGE/duplicate-detector-model"
ENV AWS_CONFIG_FILE="/root/.aws/config"
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
RUN unzip /tmp/awscliv2.zip -d /tmp
RUN /tmp/aws/install
ARG aws_access_key
ARG aws_secret_key
ENV AWS_ACCESS_KEY_ID $aws_access_key
ENV AWS_SECRET_ACCESS_KEY $aws_secret_key
RUN aws s3 sync "$DUPLICATE_DETECTOR_REMOTE_PATH" $DUPLICATE_DETECTOR_MODEL

COPY . .
COPY --from=web-builder /code/dist ./web/dist

EXPOSE 5000

CMD ["uwsgi", "uwsgi_dev.ini"]
