version: 2
jobs:
  - name: "duolingo-jeeves"
    description: |
      Jenkins Job for Continuous Deployment
    jenkins_cluster: "deployment-jenkins"
    node: "ec2-jenkins-deployment-2023"
    push: true
    timeout: 120
    command: "bash -ex jenkins-build.sh prod"
    dockerize_command: false
    slack:
      notify_aborted: true
      notify_back_to_normal: true
      notify_failure: true
      notify_repeated_failure: true
      notify_unstable: true
      room: "ci,pd-snow"
  - name: "duolingo-jeeves-health"
    description: |
      Jenkins Job for checking CI Health
    jenkins_cluster: "pr-jenkins"
    node: "ec2-jenkins-worker"
    days_to_keep: 15
    cron: "@weekly"
    timeout: 60
    command: "bash -ex jenkins-build.sh"
    dockerize_command: false
    junit: "results.xml"
    cobertura: "cobertura.xml"
    record_coverage: true
  - name: "duolingo-jeeves-pr"
    description: |
      Jenkins Job for Continuous Integration
    jenkins_cluster: "pr-jenkins"
    node: "ec2-jenkins-worker"
    concurrent_builds: true
    branch: "${sha1}"
    refspec: |-
      +refs/pull/*:refs/remotes/origin/pr/*
    trigger_phrase: "trigger ci"
    timeout: 60
    command: "bash -ex jenkins-build.sh"
    dockerize_command: false
    junit: "results.xml"
    cobertura: "cobertura.xml"
    compare_coverage: true
    recipients: |-
      ${ghprbActualCommitAuthorEmail}
  - name: "duolingo-jeeves-quick-deploy"
    description: ""
    jenkins_cluster: "deployment-jenkins"
    node: "ec2-jenkins-deployment-2023"
    log_rotator:
      days_to_keep: 60
    rebuild_settings:
      auto_rebuild: false
    parameters:
      - type: "string"
        description: |-
          BUILD_NUMBER from the last successful build for:
          <br>
          http://jenkins-ci.duolingo.com/job/duolingo-jeeves/
          <br>
          <br>
          e.g. 17
        name: "LAST_SUCCESS"
    throttle_job:
      max_concurrent_per_node: 0
      max_concurrent_total: 0
      throttle_enabled: false
    refspec: |-
      +refs/heads/*:refs/remotes/origin/*
    slack:
      notify_success: true
      notify_failure: true
      notify_repeated_failure: true
      include_custom_message: false
      commit_info: "NONE"
    timestamps: false
    command: |-
      #!/bin/bash
      set -euxf -o pipefail

      # ----- environment variables definitions -----
      TERRAFORM_PATH="galaxy/prod"
      REGISTRY="940168671796.dkr.ecr.us-east-1.amazonaws.com"

      MODULE=duolingo-jeeves-internal
      MODULE_S3_WORKER=duolingo-jeeves-s3-worker
      MODULE_WORKER_CRON=duolingo-jeeves-worker-cron


      # ----- get previously successful image -----
      ECR_REPO="$MODULE-prod"
      docker pull "$REGISTRY/$ECR_REPO:$LAST_SUCCESS"
      IMAGE_HASH=$(docker images --quiet --no-trunc --filter=reference="*/$ECR_REPO:$LAST_SUCCESS")

      # ----- deploy -----
      echo "$IMAGE_HASH" | deploy-galaxy -c -m "$MODULE" -v "$LAST_SUCCESS" -p "$TERRAFORM_PATH"
      echo "$IMAGE_HASH" | deploy-galaxy -c -m "$MODULE_S3_WORKER" -v "$LAST_SUCCESS" -p "$TERRAFORM_PATH"
      echo "$IMAGE_HASH" | deploy-galaxy -c -m "$MODULE_WORKER_CRON" -v "$LAST_SUCCESS" -p "$TERRAFORM_PATH"
    dockerize_command: false
  - name: "duolingo-jeeves-monitor-and-alarm"
    description: |-
      Pipeline that runs periodically to ensure Jeeves has up-to-date Opensearch documents.
    # This pipeline is technically a script, but we run it on client-eng-jenkins so that TRI team members can disable it and snooze notifications to #pd-snow while investigating.
    jenkins_cluster: "client-eng-jenkins"
    rebuild_settings:
      auto_rebuild: false
    parameters:
      - type: "string"
        description: "branch in duolingo-jeeves to build"
        name: "BUILD_BRANCH"
        default: "master"
      - type: "string"
        description: |-
          When testing, use C0UDM7XA4 for #slack-test Slack channel. Default to #pd-snow (C035TTWUBTN).
        name: "SLACK_CHANNEL_ID"
        default: "C035TTWUBTN"
    branch: "${BUILD_BRANCH}"
    scm:
      clone_option:
        depth: 100
    # Runs every 6 hours
    cron: "H */6 * * *"
    bindings:
      - credentials_id: "TAFTT_PROD_SLACK_TOKEN"
        variable: "SLACK_API_TOKEN"
    docker:
      compose_file: "scripts/compose.yaml"
    mailer:
      recipients: |-
        aaron.wang@duolingo.com david.sawicki@duolingo.com
  - name: |-
      duolingo-jeeves-refresh-tickets
    description: |-
      Manually trigger this job to force refresh jeeves tickets
    jenkins_cluster: "script-runner-jenkins"
    node: "ec2-jenkins-worker"
    log_rotator:
      days_to_keep: 60
    rebuild_settings:
      auto_rebuild: false
    parameters:
      - type: "choice"
        description: |-
          The target environment for which to refresh documents
        name: "ENVIRONMENT"
        choices:
          - "dev"
          - "prod"
      - type: "string"
        trim: false
        name: "BUILD_BRANCH"
        default: "master"
      - type: "string"
        description: |-
          Date in ISO format (YYYY-MM-DD) that is the end of date range (inclusive) in which to refresh documents. Defaults to current date.
        trim: false
        name: "REFRESH_END_DATE"
      - type: "string"
        description: |-
          Date in ISO format (YYYY-MM-DD) that is the beginnning of date range (inclusive) in which to refresh documents.
        trim: false
        name: "REFRESH_START_DATE"
    throttle_job:
      max_concurrent_per_node: 0
      max_concurrent_total: 0
      throttle_enabled: false
    branch: "${BUILD_BRANCH}"
    command: "bash -ex force_refresh_job.sh"
    dockerize_command: false
  - name: |-
      duolingo-jeeves-deploy-galaxy-dev
    description: |-
      Manually trigger this job to deploy to the `dev` Galaxy environment.
      <br>
      https://duolingo.atlassian.net/browse/OPS-15408
    dockerize_command: false
    jenkins_cluster: "deployment-jenkins"
    node: "ec2-jenkins-deployment-2023"
    log_rotator:
      days_to_keep: 60
    rebuild_settings:
      auto_rebuild: false
    parameters:
      - type: "string"
        trim: false
        name: "BUILD_BRANCH"
        default: "master"
      - type: "boolean"
        description: |-
          Whether to re-deploy the jeeves api and frontend
        name: "DEPLOY_API"
        default: true
      - type: "boolean"
        description: |-
          Whether to re-deploy the workers for the indexing pipeline: s3-worker, sqs-worker-1, sqs-worker-2
        name: "DEPLOY_INDEX_PIPELINE"
        default: true
      - type: "boolean"
        description: |-
          Whether to re-deploy the worker that posts daily spikes to slack
        name: "DEPLOY_SPIKE_SLACK_WORKER"
        default: true
      - type: "boolean"
        description: |-
          Whether to re-deploy the worker that checks for spike words and indexes them
        name: "DEPLOY_SPIKE_WORKER"
        default: true
      - type: "boolean"
        description: |-
          Whether to re-deploy the worker that sends bug digest emails. Doesn't run in dev.
        name: "DEPLOY_EMAIL_SENDER"
      - type: "boolean"
        description: |-
          Whether to re-deploy the worker that iterates through indexed documents and ensures embeddings are populated.
        name: |-
          DEPLOY_ENSURE_EMBEDDINGS_WORKER
        default: true
    throttle_job:
      max_concurrent_per_node: 0
      max_concurrent_total: 0
      throttle_enabled: false
    branch: "${BUILD_BRANCH}"
    timeout: 120
    command: "bash -ex jenkins-build-dev.sh"
