[uwsgi]
http-socket = :5000
wsgi-file = application.py
process = 2
threads = 2
harakiri = 300
log-format = %(addr) - %(user) [%(ltime)] "%(method) %(uri) %(proto)" %(status) %(size) "%(referer)" "%(uagent)"
route-if=equal:${HTTP_X_FORWARDED_PROTO};http redirect-permanent:https://${HTTP_HOST}${REQUEST_URI}
