[uwsgi]
buffer-size = 8192
harakiri = 300
http-socket = :5000
log-format = %(addr) - %(user) [%(ltime)] "%(method) %(uri) %(proto)" %(status) %(size) "%(referer)" "%(uagent)"
need-app = true
process = 2
threads = 50
wsgi-file = application.py
