[uwsgi]
http-socket = :5000
wsgi-file = application.py
process = 2
threads = 2
harakiri = 300
log-format = %(addr) - %(user) [%(ltime)] "%(method) %(uri) %(proto)" %(status) %(size) "%(referer)" "%(uagent)"
