rollbar:
  access_token: 9dbf3ebbc6824576aa085ffe831d303e
  enabled: False

blueprints:
  - jeeves.view.api.blueprint_api
  - jeeves.view.health.blueprint_health

opensearch:
  data_version_identifier: 5.1.6
