environment: dev

memcached:
  host: duolingo-jeeves-dev.idjnxn.cfg.use1.cache.amazonaws.com
  port: 11211

opensearch:
  #host: host.docker.internal
  #port: 9200
  host: https://vpc-duolingo-jeeves-es-dev-4xpqalvnvjkuon2qvzqyep3vxa.us-east-1.es.amazonaws.com
  port: 443

sns:
  jeeves_beta_feedback_arn: arn:aws:sns:us-east-1:940168671796:jeeves-beta-feedback
  region: us-east-1
  endpoint: "http://aws:4566"

sqs_download_verify_pipeline:
  queue_url: https://sqs.us-east-1.amazonaws.com/940168671796/jeeves-pipeline-break-download-verify-dev
  #queue_url: http://host.docker.internal:4566/000000000000/my_second_queue
  region_name: us-east-1
  endpoint_url: https://sqs.us-east-1.amazonaws.com
  #endpoint_url: http://host.docker.internal:4566

sqs_verify_index_pipeline:
  queue_url: https://sqs.us-east-1.amazonaws.com/940168671796/jeeves-pipeline-break-verify-index-dev
  #queue_url: http://host.docker.internal:4566/000000000000/your_second_queue
  region_name: us-east-1
  endpoint_url: https://sqs.us-east-1.amazonaws.com
  #endpoint_url: http://host.docker.internal:4566

s3_document_cache:
  #endpoint_url: http://host.docker.internal:4566
  bucket_name: jeeves-document-cache-dev

s3_public_static:
  bucket_name: public-static.duolingo.com

s3_internal_static:
  bucket_name: internal-static.duolingo.com

rollbar:
  enabled: True
  environment: development
  scrub_fields:
    - net_credentials
