environment: prod

memcached:
  host: duolingo-jeeves-prod.idjnxn.cfg.use1.cache.amazonaws.com
  port: 11211

elasticsearch:
  host: https://vpc-duolingo-jeeves-es-prod-eg2rc47wen2dsgmzunu4whvfju.us-east-1.es.amazonaws.com
  port: 443
