environment: prod

memcached:
  host: duolingo-jeeves-prod.idjnxn.cfg.use1.cache.amazonaws.com
  port: 11211

elasticsearch:
  host: https://vpc-duolingo-jeeves-es-prod-eg2rc47wen2dsgmzunu4whvfju.us-east-1.es.amazonaws.com
  port: 443

sns:
  jeeves_beta_feedback_arn: arn:aws:sns:us-east-1:940168671796:jeeves-beta-feedback
  region: us-east-1
  endpoint: "http://aws:4566"

sqs_download_verify_pipeline:
  queue_url: https://sqs.us-east-1.amazonaws.com/940168671796/jeeves-pipeline-break-download-verify
  region_name: us-east-1
  endpoint_url: https://sqs.us-east-1.amazonaws.com

sqs_verify_index_pipeline:
  queue_url: https://sqs.us-east-1.amazonaws.com/940168671796/jeeves-pipeline-break-verify-index
  region_name: us-east-1
  endpoint_url: https://sqs.us-east-1.amazonaws.com

s3_document_cache:
  bucket_name: jeeves-document-cache

s3_public_static:
  bucket_name: public-static.duolingo.com

s3_internal_static:
  bucket_name: internal-static.duolingo.com

rollbar:
  enabled: True
  environment: production
  scrub_fields:
    - net_credentials
